<a href="https://colab.research.google.com/github/OlgaCeban/DLSchool/blob/master/Homework2_numpy_Ceban.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b> Решение домашнего задания 2. Библиотека Numpy и линейная алгебра.
</b></h2>

---

In [0]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [0]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.50578972 0.68942086 0.78460004 ... 0.93622056 0.63604331 0.61562001]
 [0.26591344 0.14679466 0.64635091 ... 0.36602084 0.82206985 0.84107433]
 [0.08397927 0.09263253 0.045046   ... 0.33374774 0.47310233 0.68387767]
 ...
 [0.75155099 0.47363193 0.88952324 ... 0.63911116 0.18082952 0.08329731]
 [0.05762691 0.49904798 0.77408279 ... 0.80704321 0.04617682 0.11822681]
 [0.11011658 0.10032256 0.87415102 ... 0.55414769 0.02549952 0.25404226]]
[[0.40785361 0.59013672 0.63264767 ... 0.02347765 0.2674053  0.49873723]
 [0.37649895 0.21690424 0.07785161 ... 0.94126837 0.01071446 0.8437515 ]
 [0.97318485 0.03931985 0.15486525 ... 0.74925417 0.2249628  0.10181338]
 ...
 [0.19724808 0.36658889 0.43155329 ... 0.44713798 0.84157774 0.30096784]
 [0.83634484 0.83244519 0.86411437 ... 0.8781818  0.05116327 0.35490846]
 [0.39315371 0.39466363 0.92781184 ... 0.18842432 0.55720732 0.53388231]]


In [0]:
def mult(a, b):
    result = [[0 for row in range(len(b[0]))] for col in range(len(a))]

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(a[0])):
                result[i][j] += a[i][k] * b[k][j]
    return result

In [0]:
def np_mult(a, b):  
    return a.dot(b)

In [0]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 643 ms, sys: 2.49 ms, total: 646 ms
Wall time: 653 ms


In [0]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.17 ms, sys: 0 ns, total: 2.17 ms
Wall time: 11.9 ms


In [0]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.333688715021708e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.24392502 0.61120147 0.23243419] [0.8951791  0.32628044 0.54345229]


In [0]:
def scalar_product(a,b):
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]

In [0]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [0]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 23 µs, sys: 5 µs, total: 28 µs
Wall time: 30.3 µs
CPU times: user 24 µs, sys: 4 µs, total: 28 µs
Wall time: 31.5 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  b = np.asarray(a)
  b = np.diagonal(b)
  result = 0
  for i in range(len(b)):
    if b[i] % 2 == 0:
      result += b[i]
  return result

In [0]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[9, 1, 4, 3, 4],
       [1, 4, 8, 1, 1],
       [5, 2, 7, 1, 4],
       [5, 9, 8, 9, 8],
       [1, 2, 6, 5, 6]])

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 60 µs, sys: 11 µs, total: 71 µs
Wall time: 76.5 µs


10

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где s_k=\frac{x_1+...+x_k}{k}, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return np.cumsum(A, axis=1)

In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=(10**3,10**3)) 

%time S2 = np_sec_av(A)

[[8.62481127e-01 4.26504331e-01 8.66992930e-01 ... 9.77493204e-01
  8.40220595e-01 5.48377240e-01]
 [1.05512689e+00 9.43362685e-01 1.00094827e+00 ... 1.42436898e+00
  1.10477499e+00 9.22841379e-01]
 [1.73959208e+00 1.47402449e+00 1.23231061e+00 ... 1.85458738e+00
  2.00386238e+00 1.65933217e+00]
 ...
 [5.07167435e+02 5.06800474e+02 5.02874072e+02 ... 4.99437192e+02
  4.82448301e+02 4.92741722e+02]
 [5.07668266e+02 5.07444361e+02 5.03492418e+02 ... 4.99681653e+02
  4.82451702e+02 4.93570728e+02]
 [5.08204034e+02 5.07937852e+02 5.04100700e+02 ... 5.00471648e+02
  4.82817659e+02 4.94558482e+02]]
CPU times: user 17.3 ms, sys: 8 µs, total: 17.3 ms
Wall time: 16.4 ms


### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    count = 0 
    if (np.diff(a) == 0):
      count += 1
    else:
      count = 0
    return <YOUR CODE>

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    param X: array[batch_size, n]
    <YOUR CODE>
    return <YOUR CODE>

In [0]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)